### ISSUE TITLE
I tried to convert using the sample avatar, but there were no matching blend shapes...

### ISSUE THREAD

**Issue by KapDang** [enitimeago/make-it-mmd#58]
![제목 없음](https://github.com/enitimeago/make-it-mmd/assets/164660372/60cd006c-dadc-4672-903d-211836bd30cd)

I want to change from English to Japanese.
What should I do?

**Comment by enitimeago** [comment]
Apologies for the late reply.

Regarding "conversion", do you mean the import tool? Regarding the import tool, it only supports avatars where the face mesh has existing MMD blend shapes. NORANEKOSEVEN does not come with MMD blend shapes by default, so there will be no blend shapes to import. Apologies for the confusion in the BOOTH page, I believe it should be better to use an avatar like Lime.

Regarding changing from English to Japanese, it appears in your screenshot that the tool is already set to Japanese. Are you referring to the console messages? I have not considered translating these to Japanese, but I can consider this for a following release.

一応日本語でも回答させてただきますが、「convert」というのは、インポートツールのことを指しますか？インポート機能について、アバターの顔のメッシュにMMDシェイプキーが既存されていない場合はインポートできるシェイプキーはありません。NORANEKOSEVENにはMMDシェイプキーがないですので、本ツールのインポート機能はNORANEKOSEVENと使うと、インポートできるシェイプキーがありません。この勘違いはもしかしたらBOOTHページの画像ですね、混乱させてすみません。そのうちはライムちゃんなどに変更すると思います。

英語から日本語表示について、スクリーンショットによると本ツールはすでに日本語表示に設定されたみたいです。これはもしかして、unityのコンソールに現れたメッセージでしょうか。コンソールのメッセージは今までは日本語対応と検討されていないですが、今後のリリースには検討します。

**Comment by KapDang** [comment]
Yes, VRC MMD World often does not support English shape keys, so please support Japanese translation as well.

**Comment by enitimeago** [comment]
I'm closing this issue for now. Please reopen it if necessary, thank you!

For future reference: This tool only supports Japanese shape keys currently. Only Japanese shape keys can be imported, and only Japanese shape keys can be generated. English shape keys are listed in the source code, but as of version 1.1.0 these shape keys are not used.
